### ISSUE TITLE
Search project doesn't display results when some files are owned by root

### ISSUE THREAD

**Issue by rakanalh** [doomemacs/doomemacs#7932]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

First issue: 
Using `SPC s p` (`+default/search-project`), no results are displayed when there exists files in the project's directory owned by root. This specifically happens when the project has artifacts generated by a docker image that is running.

It is expected that the results would be displayed by ignoring those files

Second issue:
Even deleting those files would not restore the functionality of search project. Emacs would have to be restarted in order for results to display when searching a project.

### Current behavior

No search results are displayed.

### Steps to reproduce

1. Create a docker-compose file within any project.
```
cat -p docker-compose.postgres.yml
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./resources/dbs/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
```
2. Run the image with `docker-compose up -d`
3. Use doom-emacs to search the project... no results are displayed.

### System Information

https://gist.github.com/rakanalh/b1acccc4f76f60744125f8bc42bddfd0
